pipeline {
    agent any 
    stages {
        stage('Run test') {
            sh '''
                python -m unittest discover -v
            '''
        }
        stage('Land drone') {
            steps {
                sh '''
                    rostopic pub /drone/land std_msgs/Empty '{}' &
                    LAND_ID=$!
                    sleep 5s
                    kill $LAND_ID
                '''
            }
        }
    }
}